### ISSUE TITLE
Integrasjon med Tinder

### ISSUE THREAD

**Issue by ahusby** [kenneho/run-for-the-bus#5]
Ønsker integrasjon med Tinder, slik at jeg kan sjekke ut noen jenter mens jeg venter på bussen.

Sekundært integrasjon med http://www.travelgirls.com/ .

Tertiært (bilder av Fabio)[https://duckduckgo.com/?q=fabio+lanzoni&t=canonical&iax=1&ia=images].

Neida, jeg bare kødder. Jeg driver og lærer meg GitHub. Har opprettet min første konto nå.

**Comment by kenneho** [comment]
Haha, kreative forslag. Du får lage en pull request. 😃
